name: pocket_ssh
description: "A Pocket SSH project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  dartssh2: ^2.9.0
  flutter_secure_storage: ^9.0.0
  xterm: ^4.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2

  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0


  syncfusion_flutter_core: 27.2.5
  syncfusion_flutter_charts: 27.2.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.2
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^19.5.0



  win32: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

dependency_overrides:
  pinenacl: ^0.6.0
